#! /usr/bin/env python

"""\
%prog flatfile [yodafile]

Convert a FLAT data file to the YODA data format.
"""

import yoda, os, sys, optparse
from yoda.script_helpers import parse_x2y_args

parser = optparse.OptionParser(usage=__doc__)
opts, args = parser.parse_args()
in_out = parse_x2y_args(args, ".dat", ".yoda")
if not in_out:
    sys.stderr.write("You must specify the FLAT and YODA file names\n")
    sys.exit(1)

for i, o in in_out:
    analysisobjects = yoda.readFLAT(i)
    yoda.writeYODA(analysisobjects, o)
